    version: "3.9"

    services:
      app:
        container_name: jira-app
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://jira-db:5432/jira
          SPRING_DATASOURCE_USERNAME: jira
          SPRING_DATASOURCE_PASSWORD: JiraRush
          SPRING_PROFILES_ACTIVE: prod

      nginx:
        container_name: nginx
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./resources/static:/opt/jirarush/resources/static
          - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - app

      db:
        container_name: jira-db
        image: postgres
        environment:
          POSTGRES_USER: jira
          POSTGRES_PASSWORD: JiraRush
          POSTGRES_DB: jira
        volumes:
          - db_data:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U jira" ]
          interval: 5s
          retries: 5

    volumes:
      db_data: